apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-operator
  labels:
    control-plane: medusa-operator
spec:
  selector:
    matchLabels:
      control-plane: medusa-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: medusa-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: k8ssandra/medusa-operator:latest
        name: manager
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
